name: internship_ad_stacks
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  table_calendar: ^3.1.2
  
  flutter_gen: ^5.12.0
  

dev_dependencies:
  build_runner: ^2.8.0
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
  line_length: 120
